const os = require('os');
const fs = require('fs');
const path = require('path');

const SKIP_KEYWORDS = ['Tailscale', 'vEthernet', 'Loopback', 'VMware', 'VirtualBox', 'Pseudo'];

function parseDotEnv(filePath) {
  const result = {};
  if (!fs.existsSync(filePath)) return result;

  const lines = fs.readFileSync(filePath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    result[key] = value;
  }

  return result;
}

function getLocalIP() {
  const interfaces = os.networkInterfaces();
  const candidates = [];

  for (const [name, addrs] of Object.entries(interfaces)) {
    if (SKIP_KEYWORDS.some((kw) => name.includes(kw))) continue;

    for (const iface of addrs) {
      if (iface.family === 'IPv4' && !iface.internal) {
        candidates.push({ name, address: iface.address });
      }
    }
  }

  if (candidates.length === 0) return null;

  const preferred =
    candidates.find((candidate) => /ethernet/i.test(candidate.name) && !/vethernet/i.test(candidate.name)) ||
    candidates.find((candidate) => /wi.fi|wlan|wireless/i.test(candidate.name)) ||
    candidates[0];

  return preferred?.address || null;
}

(function main() {
  const rootDir = path.join(__dirname, '..');
  const feDir = path.join(rootDir, 'cms-middle-fe');
  const rootEnvFile = path.join(rootDir, '.env');
  const rootEnvGeneratedFile = path.join(rootDir, '.env.generated');
  const feEnvLocalFile = path.join(feDir, '.env.local');

  const fallback = parseDotEnv(rootEnvFile);
  const detectedIP = getLocalIP();
  const localIP = detectedIP || '127.0.0.1';

  if (!detectedIP) {
    console.warn(`[detect-ip] No usable LAN IPv4 found. Using ${localIP}.`);
  } else {
    console.log(`[detect-ip] Detected LAN IPv4: ${localIP}`);
  }

  const fePort = fallback.FE_PORT || '5173';
  const beHost = fallback.BE_HOST || localIP;
  const bePort = fallback.BE_PORT || '5050';

  const feEnvContent = `# Auto-generated by scripts/detect-ip.js - DO NOT EDIT MANUALLY
VITE_HOST=${localIP}
VITE_PORT=${fePort}
VITE_BE_HOST=${beHost}
VITE_BE_PORT=${bePort}
`;

  const sharedEnvContent = `# Auto-generated by scripts/detect-ip.js - DO NOT EDIT MANUALLY
LOCAL_IP=${localIP}
FE_PORT=${fePort}
BE_HOST=${beHost}
BE_PORT=${bePort}
`;

  fs.writeFileSync(feEnvLocalFile, feEnvContent, 'utf-8');
  fs.writeFileSync(rootEnvGeneratedFile, sharedEnvContent, 'utf-8');

  console.log(`[detect-ip] Wrote FE env: ${feEnvLocalFile}`);
  console.log(`[detect-ip] Wrote shared env: ${rootEnvGeneratedFile}`);
})();
